name: Synopsys Security Testing (Polaris SAST+SCA)

on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:

jobs:      
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: install npm
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          
      - name: install dependency
        run: |
          npm install --no-audit --no-fund --silent
          mkdir ./sarifs
          mkdir ./processed-sarifs

      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@v1.9.0
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: "APAC-SG-github-demo"
          polaris_project_name: "WebGoat"
          polaris_assessment_types: "SCA,SAST"
          polaris_prComment_enabled: true
          polaris_prComment_severities: "high,critical,medium,low"
          github_token: ${{ secrets.GITHUB_TOKEN }}

          ### SARIF report generation and upload to GitHub Adavanced Security Tab
          polaris_reports_sarif_create: true
          polaris_reports_sarif_groupSCAIssues: true
          polaris_upload_sarif_report: true
          polaris_reports_sarif_file_path: './sarifs/report.sarif.json'


      - name: Add SCW Training
        uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@v1
        if: always()
        with:
          inputSarifFile: ./sarifs/*.json
          outputSarifFile: ./processed-sarifs
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: ./processed-sarifs
          category: AppSec
